#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.6f1_5c3fb0a11183"
#define UNITY_VERSION_FULL_NICE "2019.3.6f1 (5c3fb0a11183)"
#define UNITY_VERSION_BLD 6045616
#define UNITY_VERSION_DATE 1584499918
#define UNITY_VERSION_WIN "2019.3.6.6045616"
#define UNITY_VERSION_BRANCH "2019.3/staging"
